WIP

diff --git a/keycloak/healthcheck b/keycloak/healthcheck
--- a/keycloak/healthcheck
+++ b/keycloak/healthcheck
@@ -1,9 +1,9 @@
 #!/bin/bash
 
-# opening file descriptor for read/write
+# Opening file descriptor for read/write
 exec 3<>/dev/tcp/localhost/8080
 
-# sending HTTP request
+# Sending HTTP request
 cat >&3 <<EOF
 HEAD /health/ready HTTP/1.1
 Host: localhost:8080
@@ -11,21 +11,20 @@ Connection: close
 
 EOF
 
-# reading HTTP response
-response=$(timeout 1 cat <&3)
+# Reading HTTP response
+response="$(timeout 1 cat <&3)"
 
-# closing file descriptor
+# Closing file descriptor
 exec 3<&-
 exec 3>&-
 
-# check HTTP response
-case $response in
+# Check HTTP response
+case "${response}" in
 HTTP/1.[01]\ 200\ *)
     exit 0
     ;;
 *)
-    echo "Incorrect response:"
-    echo "$response"
+    echo "Error Response: ${response}" >&2
     exit 1
     ;;
 esac
