make GEYSER_MODE mandatory, and automatically added to configuration

diff --git a/scripts/compose b/scripts/compose
--- a/scripts/compose
+++ b/scripts/compose
@@ -5,20 +5,16 @@
 # Distributed under the GNU Affero General Public License, version 3.          #
 ################################################################################
 
-# This script is a shorthand to run Docker Compose commands.
+# This script is a shorthand to run Docker Compose commands with the environment
+# corresponding to $GEYSER_MODE (development or production).
 
 : "${GEYSER_DIR:=$(dirname "$0")/..}"
-
-if [[ -z "$GEYSER_MODE" ]]; then
-  echo "Warning: GEYSER_MODE is not set; defaulting to production mode" >&2
-  GEYSER_MODE=production
-fi
 
 if [[ $GEYSER_MODE == "production" ]]; then
   docker compose --env-file "$GEYSER_DIR"/.env.prod --env-file "$GEYSER_DIR"/.env.local -f "$GEYSER_DIR"/compose.yaml -f "$GEYSER_DIR"/compose.prod.yaml "$@"
 elif [[ $GEYSER_MODE == "development" ]]; then
   docker compose --env-file "$GEYSER_DIR"/.env.dev --env-file "$GEYSER_DIR"/.env.local -f "$GEYSER_DIR"/compose.yaml "$@"
 else
-  echo "Error: Incorrect mode $GEYSER_MODE" >&2
+  echo "Error: GEYSER_MODE must be set to 'development' or 'production'" >&2
   exit 1
 fi
diff --git a/scripts/geyser b/scripts/geyser
--- a/scripts/geyser
+++ b/scripts/geyser
@@ -13,7 +13,6 @@ set -e
 : "${GEYSER_DIR:=$(dirname "$0")/..}"
 
 # Options
-: "${GEYSER_MODE:=production}"
 for arg in "$@"; do
   shift
   case "$arg" in
@@ -31,6 +30,12 @@ for arg in "$@"; do
     ;;
   esac
 done
+if [[ "$GEYSER_MODE" != 'development' ]] && [[ "$GEYSER_MODE" != 'production' ]]
+then
+  echo "Error: the mode (development/production) must be set, using either \
+        options --dev/--prod, or the environment variable GEYSER_MODE" >&2
+  exit 1
+fi
 export GEYSER_MODE
 
 ignore_extra_args () {
